#!/usr/bin/with-contenv bash

# If we are debugging, enable trace
if [ "${DEBUG,,}" = "true" ]; then
  set -x
fi

. /unicorn-common.sh

readVarFromConf "UnicornFFMPEG_version" installedVersion

getVersionInfo "UnicornFFMPEG" remoteVersion remoteFile

if [ -z "${remoteVersion}" ] || [ -z "${remoteFile}" ]; then
  echo "Could not get update version"
else
  if [ "${remoteVersion}" != "${installedVersion}" ]; then
    echo "Attempting to upgrade to: ${remoteVersion}"
    installFromUrl "${remoteFile}"
    npm install --prefix=/opt/UnicornFFMPEG
    npm start --prefix=/opt/UnicornFFMPEG
  fi
fi

if [ ! -f "/opt/UnicornFFMPEG/bin/Plex Transcoder-linux" ]; then
  echo "UnicornFFMPEG not installed."
  exit 1
fi

[ -f "/usr/lib/plexmediaserver/Plex Relay" ] && rm -f "/usr/lib/plexmediaserver/Plex Relay"
[ -f "/usr/lib/plexmediaserver/Plex Transcoder" ] && rm -f "/usr/lib/plexmediaserver/Plex Transcoder"

cp -f "/opt/UnicornFFMPEG/bin/Plex Transcoder-linux" "/usr/lib/plexmediaserver/Plex Transcoder"
