#!/usr/bin/with-contenv bash

export APPLY_IPTABLES="${APPLY_IPTABLES:-false}"

if [ "${APPLY_IPTABLES}" == "true" ]; then
  # Allow LAN traffic to 32400
  $(iptables -C INPUT -p tcp -s localhost --dport 32400 -j ACCEPT &>/dev/null) || iptables -A INPUT -p tcp -s localhost --dport 32400 -j ACCEPT
  # Block WAN traffic to 32400
  $(iptables -C INPUT -p tcp --dport 32400 -j DROP &>/dev/null) || iptables -A INPUT -p tcp --dport 32400 -j DROP
else
  # Clear rules
  $(iptables -C INPUT -p tcp -s localhost --dport 32400 -j ACCEPT &>/dev/null) && iptables -D INPUT -p tcp -s localhost --dport 32400 -j ACCEPT
  $(iptables -C INPUT -p tcp --dport 32400 -j DROP &>/dev/null) && iptables -D INPUT -p tcp --dport 32400 -j DROP
fi



